### ISSUE TITLE
LICENSE file not included in Swift package

### ISSUE THREAD

**Issue by deni2s** [CreateAPI/URLQueryEncoder#5]
Looks like when installing as swift package the LICENSE file is not included in the package of 0.2.0.
So automated license collecting tools like https://github.com/nicklockwood/Tribute can't read the license.
Seems like the LICENSE file was added after 0.2.0, maybe just the version number needs to be increased?

**Comment by liamnichols** [comment]
Thanks @deni2s for raising this, I didn't know such tools existed so never published a release after adding the file. I've just published [0.2.1](https://github.com/CreateAPI/URLQueryEncoder/releases/tag/0.2.1) to address this!

**Comment by deni2s** [comment]
Thanks, @liamnichols !
